def summarize(text):
    # import pipeline function to use huggingface models
    from transformers import pipeline

    # define the pipeline as summarization and specify the model - we're training our own later
    pipe = pipeline('summarization', model='facebook/bart-large-cnn')
    response = pipe(text)
    # print specifically the summary from the dictionary generated by the pipe
    summary_text = response[0]['summary_text']

    # return the text to the sender
    return summary_text

